version: '3'

services: 
  app:
    container_name: php
    build: ./config/php
    volumes: 
      - ./:/var/www/html
    ports: 
      - 8080:80
  db:
    container_name: mysql
    build: ./config/sql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phpapp
      - MYSQL_user=phpadmin
      - MYSQL_PASSWORD=phpadmin
  admin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root     # should be 'root'
      - PMA_PASSWORD=root # should make same to MYSQL_ROOT_PASSWORD
    ports:
      - 8081:80 